//! Property tests generated by the quoin `spec-correctness` skill.
//!
//! Source: `quire properties --scope . --json 'spec/**/*.md'` (quire-cli 0.12.0).
//! Tests for FR-040: edge-type vocabulary and `allowed_links` normalization.
//!
//! `property=round-trip` in the provenance lines below records what the
//! classifier reported. Grounding re-derived the strategy as a normalization
//! property over the two authoring forms (`label-from-mention`: the criterion
//! names the array→map rewrite, it does not compose a function with its
//! inverse). The classifier is not wrong to label it; the generator is not
//! obliged to take the label literally.

use proptest::prelude::*;
use quire_rs::vocab::{normalize_allowed_links, AllowedLinks};
use serde_json::{json, Value};

/// Verb tokens as they appear in a module manifest.
fn verb() -> impl Strategy<Value = String> {
    "[a-z][a-z_]{2,14}"
}

proptest! {
    /// Trace: FR-040-AC-4 — `allowed_links` in array form normalizes to a map
    /// whose every verb allows any target.
    /// spec-correctness: row=FR-040-AC-4 property=round-trip extraction=extractable origin=regex review=none
    #[test]
    fn fr_040_ac_4_array_form_allows_any_target(verbs in prop::collection::vec(verb(), 0..16)) {
        let value = Value::Array(verbs.iter().map(|v| json!(v)).collect());
        let normalized = normalize_allowed_links(Some(&value));

        // Every declared verb is present, and each allows any target.
        for v in &verbs {
            prop_assert_eq!(normalized.get(v), Some(&vec!["*".to_string()]));
        }
        // Nothing is invented: the key set is exactly the declared verb set.
        let declared: std::collections::BTreeSet<&String> = verbs.iter().collect();
        let got: std::collections::BTreeSet<&String> = normalized.keys().collect();
        prop_assert_eq!(got, declared);
    }

    /// Trace: FR-040-AC-4 — `allowed_links` in map form is preserved, target
    /// lists included.
    /// spec-correctness: row=FR-040-AC-4 property=round-trip extraction=extractable origin=regex review=none
    #[test]
    fn fr_040_ac_4_map_form_preserves_target_lists(
        pairs in prop::collection::vec((verb(), prop::collection::vec(verb(), 0..4)), 0..12)
    ) {
        let mut object = serde_json::Map::new();
        for (v, targets) in &pairs {
            object.insert(v.clone(), Value::Array(targets.iter().map(|t| json!(t)).collect()));
        }
        let value = Value::Object(object.clone());
        let normalized = normalize_allowed_links(Some(&value));

        let expected: AllowedLinks = object
            .iter()
            .map(|(v, targets)| {
                let targets = targets
                    .as_array()
                    .map(|a| a.iter().filter_map(|t| t.as_str().map(str::to_string)).collect())
                    .unwrap_or_default();
                (v.clone(), targets)
            })
            .collect();
        prop_assert_eq!(normalized, expected);
    }

    /// Trace: FR-040-AC-4 — anything that is neither an array nor a map yields
    /// an empty map rather than a partial one.
    /// spec-correctness: row=FR-040-AC-4 property=round-trip extraction=extractable origin=regex review=none
    #[test]
    fn fr_040_ac_4_other_shapes_yield_empty(scalar in prop_oneof![
        Just(Value::Null),
        Just(Value::Bool(true)),
        any::<i64>().prop_map(|n| json!(n)),
        "[a-z]{0,8}".prop_map(|s| json!(s)),
    ]) {
        prop_assert!(normalize_allowed_links(Some(&scalar)).is_empty());
    }
}

/// Trace: FR-040-AC-4 — an absent `allowed_links` yields an empty map.
/// spec-correctness: row=FR-040-AC-4 property=round-trip extraction=extractable origin=regex review=none
#[test]
fn fr_040_ac_4_absent_yields_empty() {
    assert!(normalize_allowed_links(None).is_empty());
}

/// TC-895, FR-040-AC-4 (CR-069, Property): `allowed_links` normalization is a
/// **fixpoint** — re-serializing a normalized map and normalizing it again
/// yields the same map. Array form and map form are two authoring spellings of
/// one value, and this is what says the normalized form is the canonical one
/// rather than merely *a* form.
mod props_metamorphic {
    use super::*;

    /// The map form of an already-normalized `AllowedLinks`.
    fn to_value(links: &AllowedLinks) -> Value {
        Value::Object(
            links
                .iter()
                .map(|(verb, targets)| {
                    (
                        verb.clone(),
                        Value::Array(targets.iter().map(|t| json!(t)).collect()),
                    )
                })
                .collect(),
        )
    }

    proptest! {
        #![proptest_config(ProptestConfig::with_cases(3000))]

        /// spec-correctness: row=FR-040-AC-4 property=fixpoint extraction=extractable origin=manual review=none
        #[test]
        fn tc895_normalization_reaches_a_fixpoint(verbs in prop::collection::vec(verb(), 0..12)) {
            // Array form is the lossier spelling; normalizing it once must land
            // on a value that normalizes to itself.
            let array = Value::Array(verbs.iter().map(|v| json!(v)).collect());
            let once = normalize_allowed_links(Some(&array));
            let twice = normalize_allowed_links(Some(&to_value(&once)));
            prop_assert_eq!(twice, once);
        }

        /// spec-correctness: row=FR-040-AC-4 property=fixpoint extraction=extractable origin=manual review=none
        #[test]
        fn tc895_map_form_is_already_a_fixpoint(
            pairs in prop::collection::vec((verb(), prop::collection::vec(verb(), 0..4)), 0..10)
        ) {
            let mut object = serde_json::Map::new();
            for (v, targets) in &pairs {
                object.insert(v.clone(), Value::Array(targets.iter().map(|t| json!(t)).collect()));
            }
            let once = normalize_allowed_links(Some(&Value::Object(object)));
            let twice = normalize_allowed_links(Some(&to_value(&once)));
            prop_assert_eq!(twice, once);
        }
    }
}
