//! Property tests generated by the quoin `spec-correctness` skill.
//!
//! Source: `quire properties --scope . --json 'spec/**/*.md'` (quire-cli 0.12.0).
//! Tests for FR-040: edge-type vocabulary and `allowed_links` normalization.
//!
//! `property=round-trip` in the provenance lines below records what the
//! classifier reported. Grounding re-derived the strategy as a normalization
//! property over the two authoring forms (`label-from-mention`: the criterion
//! names the array→map rewrite, it does not compose a function with its
//! inverse). The classifier is not wrong to label it; the generator is not
//! obliged to take the label literally.

use proptest::prelude::*;
use quire_rs::vocab::{normalize_allowed_links, AllowedLinks};
use serde_json::{json, Value};

/// Verb tokens as they appear in a module manifest.
fn verb() -> impl Strategy<Value = String> {
    "[a-z][a-z_]{2,14}"
}

proptest! {
    /// Trace: FR-040-AC-4 — `allowed_links` in array form normalizes to a map
    /// whose every verb allows any target.
    /// spec-correctness: row=FR-040-AC-4 property=round-trip extraction=extractable origin=regex review=none
    #[test]
    fn fr_040_ac_4_array_form_allows_any_target(verbs in prop::collection::vec(verb(), 0..16)) {
        let value = Value::Array(verbs.iter().map(|v| json!(v)).collect());
        let normalized = normalize_allowed_links(Some(&value));

        // Every declared verb is present, and each allows any target.
        for v in &verbs {
            prop_assert_eq!(normalized.get(v), Some(&vec!["*".to_string()]));
        }
        // Nothing is invented: the key set is exactly the declared verb set.
        let declared: std::collections::BTreeSet<&String> = verbs.iter().collect();
        let got: std::collections::BTreeSet<&String> = normalized.keys().collect();
        prop_assert_eq!(got, declared);
    }

    /// Trace: FR-040-AC-4 — `allowed_links` in map form is preserved, target
    /// lists included.
    /// spec-correctness: row=FR-040-AC-4 property=round-trip extraction=extractable origin=regex review=none
    #[test]
    fn fr_040_ac_4_map_form_preserves_target_lists(
        pairs in prop::collection::vec((verb(), prop::collection::vec(verb(), 0..4)), 0..12)
    ) {
        let mut object = serde_json::Map::new();
        for (v, targets) in &pairs {
            object.insert(v.clone(), Value::Array(targets.iter().map(|t| json!(t)).collect()));
        }
        let value = Value::Object(object.clone());
        let normalized = normalize_allowed_links(Some(&value));

        let expected: AllowedLinks = object
            .iter()
            .map(|(v, targets)| {
                let targets = targets
                    .as_array()
                    .map(|a| a.iter().filter_map(|t| t.as_str().map(str::to_string)).collect())
                    .unwrap_or_default();
                (v.clone(), targets)
            })
            .collect();
        prop_assert_eq!(normalized, expected);
    }

    /// Trace: FR-040-AC-4 — anything that is neither an array nor a map yields
    /// an empty map rather than a partial one.
    /// spec-correctness: row=FR-040-AC-4 property=round-trip extraction=extractable origin=regex review=none
    #[test]
    fn fr_040_ac_4_other_shapes_yield_empty(scalar in prop_oneof![
        Just(Value::Null),
        Just(Value::Bool(true)),
        any::<i64>().prop_map(|n| json!(n)),
        "[a-z]{0,8}".prop_map(|s| json!(s)),
    ]) {
        prop_assert!(normalize_allowed_links(Some(&scalar)).is_empty());
    }
}

/// Trace: FR-040-AC-4 — an absent `allowed_links` yields an empty map.
/// spec-correctness: row=FR-040-AC-4 property=round-trip extraction=extractable origin=regex review=none
#[test]
fn fr_040_ac_4_absent_yields_empty() {
    assert!(normalize_allowed_links(None).is_empty());
}
