//! Schema bundle embedded at compile time (FR-069 Inputs).
//!
//! The real reason semantic-core bytes must be *embedded* (rather than read
//! at call time from a registry, a module, or the filesystem) is
//! `properties.rs`'s and `clauses.rs`'s internal gate: `field_decl_validator`
//! and `model_validator` synthesize a throwaway schema that `$ref`s straight
//! into the semantic-core bundle to validate a `FieldDecl`/`ClauseRef`/etc.
//! record quire-rs *itself* just produced, deep inside extraction with no
//! registry, module, or caller in scope (`&|_| None` for the sibling
//! resolver) — so the only bytes available to validate against are whatever
//! this module has compiled in. This is unrelated to the `wasm` feature: no
//! `wasm`-gated code path reads the filesystem, and the resolver
//! (`resolver.rs`) never did — that used to be this file's stated reason,
//! and it was false.
//!
//! `MODULE_MANIFEST_SCHEMA` and `PROVENANCE` still `include_str!` a file
//! committed under `schemas/vendored/` — the one piece of this crate that
//! remains an actual vendored copy, blocked on `agent-ix/filament-core-data`
//! publishing its `module-semantic-block.schema.json` as the replacement
//! (coordinate through the de-vendoring effort, not by copying further).
//!
//! `SEMANTIC_CORE_VERSIONS`, `SEMANTIC_CORE_<version>`, and
//! `semantic_core_bundle` are generated by `build.rs` at compile time from
//! the published `@agent-ix/semantic-core` npm package at each pinned
//! version — never from a file committed to this repository.

/// The `semantic.contract_version` this engine understands.
pub const CONTRACT_VERSION: &str = "1.0.0";
/// Base of every semantic-core `$id`.
pub const SEMANTIC_CORE_BASE: &str = "https://schemas.agent-ix.org/semantic-core/";
/// Base of every module-emitted `$id`.
pub const MODULE_SCHEMA_BASE: &str = "https://schemas.agent-ix.org/";

pub const MODULE_MANIFEST_SCHEMA: &str =
    include_str!("../../schemas/vendored/module-manifest.schema.json");
pub const PROVENANCE: &str = include_str!("../../schemas/vendored/PROVENANCE.json");

include!(concat!(env!("OUT_DIR"), "/embedded_semantic_core.rs"));
