//! Vendored schema bundle embedded at compile time (FR-069 Inputs).
//!
//! GENERATED by scripts/vendor-semantic-schemas.sh from schemas/vendored/;
//! do not edit. Embedding (rather than reading the filesystem) is what lets
//! the resolver run unchanged under the `wasm` feature (FR-069-AC-5).

/// The `semantic.contract_version` this engine understands.
pub const CONTRACT_VERSION: &str = "1.0.0";
/// Base of every semantic-core `$id`.
pub const SEMANTIC_CORE_BASE: &str = "https://schemas.agent-ix.org/semantic-core/";
/// Base of every module-emitted `$id`.
pub const MODULE_SCHEMA_BASE: &str = "https://schemas.agent-ix.org/";

pub const MODULE_MANIFEST_SCHEMA: &str =
    include_str!("../../schemas/vendored/module-manifest.schema.json");
pub const COMMON_SCHEMA: &str = include_str!("../../schemas/vendored/common.schema.json");
pub const PROVENANCE: &str = include_str!("../../schemas/vendored/PROVENANCE.json");

/// Semantic-core versions with an embedded bundle, ascending.
pub const SEMANTIC_CORE_VERSIONS: &[&str] = &["0.1.0"];

/// `(file name, bytes)` for every schema of semantic-core 0.1.0, sorted by name;
/// `toolchain.json` is provenance, not a schema, and is excluded.
pub const SEMANTIC_CORE_0_1_0: &[(&str, &str)] = &[
    (
        "ClauseLanguage.json",
        include_str!("../../schemas/vendored/semantic-core/0.1.0/ClauseLanguage.json"),
    ),
    (
        "ClauseRef.json",
        include_str!("../../schemas/vendored/semantic-core/0.1.0/ClauseRef.json"),
    ),
    (
        "ConstraintDecl.json",
        include_str!("../../schemas/vendored/semantic-core/0.1.0/ConstraintDecl.json"),
    ),
    (
        "ConstraintKeyword.json",
        include_str!("../../schemas/vendored/semantic-core/0.1.0/ConstraintKeyword.json"),
    ),
    (
        "DecimalPolicy.json",
        include_str!("../../schemas/vendored/semantic-core/0.1.0/DecimalPolicy.json"),
    ),
    (
        "DefaultDecl.json",
        include_str!("../../schemas/vendored/semantic-core/0.1.0/DefaultDecl.json"),
    ),
    (
        "DefaultKind.json",
        include_str!("../../schemas/vendored/semantic-core/0.1.0/DefaultKind.json"),
    ),
    (
        "EdgeCategory.json",
        include_str!("../../schemas/vendored/semantic-core/0.1.0/EdgeCategory.json"),
    ),
    (
        "EnumValue.json",
        include_str!("../../schemas/vendored/semantic-core/0.1.0/EnumValue.json"),
    ),
    (
        "EnumValuesConstraint.json",
        include_str!("../../schemas/vendored/semantic-core/0.1.0/EnumValuesConstraint.json"),
    ),
    (
        "ExclusiveMaxConstraint.json",
        include_str!("../../schemas/vendored/semantic-core/0.1.0/ExclusiveMaxConstraint.json"),
    ),
    (
        "ExclusiveMinConstraint.json",
        include_str!("../../schemas/vendored/semantic-core/0.1.0/ExclusiveMinConstraint.json"),
    ),
    (
        "FieldDecl.json",
        include_str!("../../schemas/vendored/semantic-core/0.1.0/FieldDecl.json"),
    ),
    (
        "FormatConstraint.json",
        include_str!("../../schemas/vendored/semantic-core/0.1.0/FormatConstraint.json"),
    ),
    (
        "Identifier.json",
        include_str!("../../schemas/vendored/semantic-core/0.1.0/Identifier.json"),
    ),
    (
        "KernelScalar.json",
        include_str!("../../schemas/vendored/semantic-core/0.1.0/KernelScalar.json"),
    ),
    (
        "MaxConstraint.json",
        include_str!("../../schemas/vendored/semantic-core/0.1.0/MaxConstraint.json"),
    ),
    (
        "MaxLengthConstraint.json",
        include_str!("../../schemas/vendored/semantic-core/0.1.0/MaxLengthConstraint.json"),
    ),
    (
        "MinConstraint.json",
        include_str!("../../schemas/vendored/semantic-core/0.1.0/MinConstraint.json"),
    ),
    (
        "MinLengthConstraint.json",
        include_str!("../../schemas/vendored/semantic-core/0.1.0/MinLengthConstraint.json"),
    ),
    (
        "Multiplicity.json",
        include_str!("../../schemas/vendored/semantic-core/0.1.0/Multiplicity.json"),
    ),
    (
        "NonEmptyConstraint.json",
        include_str!("../../schemas/vendored/semantic-core/0.1.0/NonEmptyConstraint.json"),
    ),
    (
        "OperationDecl.json",
        include_str!("../../schemas/vendored/semantic-core/0.1.0/OperationDecl.json"),
    ),
    (
        "PatternConstraint.json",
        include_str!("../../schemas/vendored/semantic-core/0.1.0/PatternConstraint.json"),
    ),
    (
        "RelationDecl.json",
        include_str!("../../schemas/vendored/semantic-core/0.1.0/RelationDecl.json"),
    ),
    (
        "SemanticId.json",
        include_str!("../../schemas/vendored/semantic-core/0.1.0/SemanticId.json"),
    ),
    (
        "SourceLocus.json",
        include_str!("../../schemas/vendored/semantic-core/0.1.0/SourceLocus.json"),
    ),
    (
        "TypeRef.json",
        include_str!("../../schemas/vendored/semantic-core/0.1.0/TypeRef.json"),
    ),
    (
        "UniqueConstraint.json",
        include_str!("../../schemas/vendored/semantic-core/0.1.0/UniqueConstraint.json"),
    ),
    (
        "UnitSymbol.json",
        include_str!("../../schemas/vendored/semantic-core/0.1.0/UnitSymbol.json"),
    ),
];

/// The embedded bundle for `version`, if any.
pub fn semantic_core_bundle(version: &str) -> Option<&'static [(&'static str, &'static str)]> {
    match version {
        "0.1.0" => Some(SEMANTIC_CORE_0_1_0),
        _ => None,
    }
}
