//! Vendored schema bundle embedded at compile time (FR-069 Inputs).
//!
//! `module-manifest.schema.json` and `PROVENANCE.json` are GENERATED by
//! scripts/vendor-semantic-schemas.sh from schemas/vendored/; do not edit
//! those by hand. `COMMON_SCHEMA` and the semantic-core 0.2.0 bundle are
//! resolved through the `filament-core-data` dependency instead (PLAT-906) —
//! `build.rs` copies them into `OUT_DIR` at build time; nothing under
//! `schemas/vendored/` backs them. Embedding (rather than reading the
//! filesystem at runtime) is what lets the resolver run unchanged under the
//! `wasm` feature either way (FR-069-AC-5).
//!
//! There is no semantic-core 0.1.0 bundle (PLAT-906): no commit of
//! `filament-core-data` carries both a Cargo package and 0.1.0-vintage schema
//! bytes (its workspace was added in the same commit that bumped
//! semantic-core to 0.2.0), so 0.1.0 has no dependency edge to resolve
//! through, and quire-rs no longer carries a committed copy of it either.
//! `semantic_core_bundle("0.1.0")` returns `None`; a module declaring
//! `semantic_core: 0.1.0` fails to load until `filament-core-data` publishes
//! 0.1.0 in a resolvable form (see the PLAT-906 PR description).

/// The `semantic.contract_version` this engine understands.
pub const CONTRACT_VERSION: &str = "1.0.0";
/// Base of every semantic-core `$id`.
pub const SEMANTIC_CORE_BASE: &str = "https://schemas.agent-ix.org/semantic-core/";
/// Base of every module-emitted `$id`.
pub const MODULE_SCHEMA_BASE: &str = "https://schemas.agent-ix.org/";

pub const MODULE_MANIFEST_SCHEMA: &str =
    include_str!("../../schemas/vendored/module-manifest.schema.json");
/// filament-core-data's `schema/semantic/v1/common.schema.json`, copied into
/// `OUT_DIR` by `build.rs` from the pinned dependency checkout.
pub const COMMON_SCHEMA: &str = include_str!(concat!(env!("OUT_DIR"), "/common.schema.json"));
pub const PROVENANCE: &str = include_str!("../../schemas/vendored/PROVENANCE.json");

/// Semantic-core versions with an embedded bundle, ascending. There is no
/// 0.1.0 entry — see the module doc comment.
pub const SEMANTIC_CORE_VERSIONS: &[&str] = &["0.2.0"];

/// `(file name, bytes)` for every schema of semantic-core 0.2.0, sorted by
/// name, copied into `OUT_DIR` by `build.rs` from the pinned
/// `filament-core-data` dependency checkout (PLAT-906) — nothing under
/// `schemas/vendored/` backs this version. `toolchain.json` is provenance,
/// not a schema, and is excluded.
pub const SEMANTIC_CORE_0_2_0: &[(&str, &str)] = &[
    (
        "ClauseLanguage.json",
        include_str!(concat!(
            env!("OUT_DIR"),
            "/semantic-core-0.2.0/ClauseLanguage.json"
        )),
    ),
    (
        "ClauseRef.json",
        include_str!(concat!(
            env!("OUT_DIR"),
            "/semantic-core-0.2.0/ClauseRef.json"
        )),
    ),
    (
        "ConstraintDecl.json",
        include_str!(concat!(
            env!("OUT_DIR"),
            "/semantic-core-0.2.0/ConstraintDecl.json"
        )),
    ),
    (
        "ConstraintKeyword.json",
        include_str!(concat!(
            env!("OUT_DIR"),
            "/semantic-core-0.2.0/ConstraintKeyword.json"
        )),
    ),
    (
        "DecimalPolicy.json",
        include_str!(concat!(
            env!("OUT_DIR"),
            "/semantic-core-0.2.0/DecimalPolicy.json"
        )),
    ),
    (
        "DefaultDecl.json",
        include_str!(concat!(
            env!("OUT_DIR"),
            "/semantic-core-0.2.0/DefaultDecl.json"
        )),
    ),
    (
        "DefaultKind.json",
        include_str!(concat!(
            env!("OUT_DIR"),
            "/semantic-core-0.2.0/DefaultKind.json"
        )),
    ),
    (
        "EdgeCategory.json",
        include_str!(concat!(
            env!("OUT_DIR"),
            "/semantic-core-0.2.0/EdgeCategory.json"
        )),
    ),
    (
        "EnumValue.json",
        include_str!(concat!(
            env!("OUT_DIR"),
            "/semantic-core-0.2.0/EnumValue.json"
        )),
    ),
    (
        "EnumValuesConstraint.json",
        include_str!(concat!(
            env!("OUT_DIR"),
            "/semantic-core-0.2.0/EnumValuesConstraint.json"
        )),
    ),
    (
        "ExclusiveMaxConstraint.json",
        include_str!(concat!(
            env!("OUT_DIR"),
            "/semantic-core-0.2.0/ExclusiveMaxConstraint.json"
        )),
    ),
    (
        "ExclusiveMinConstraint.json",
        include_str!(concat!(
            env!("OUT_DIR"),
            "/semantic-core-0.2.0/ExclusiveMinConstraint.json"
        )),
    ),
    (
        "FieldDecl.json",
        include_str!(concat!(
            env!("OUT_DIR"),
            "/semantic-core-0.2.0/FieldDecl.json"
        )),
    ),
    (
        "FormatConstraint.json",
        include_str!(concat!(
            env!("OUT_DIR"),
            "/semantic-core-0.2.0/FormatConstraint.json"
        )),
    ),
    (
        "Identifier.json",
        include_str!(concat!(
            env!("OUT_DIR"),
            "/semantic-core-0.2.0/Identifier.json"
        )),
    ),
    (
        "KernelScalar.json",
        include_str!(concat!(
            env!("OUT_DIR"),
            "/semantic-core-0.2.0/KernelScalar.json"
        )),
    ),
    (
        "MaxConstraint.json",
        include_str!(concat!(
            env!("OUT_DIR"),
            "/semantic-core-0.2.0/MaxConstraint.json"
        )),
    ),
    (
        "MaxLengthConstraint.json",
        include_str!(concat!(
            env!("OUT_DIR"),
            "/semantic-core-0.2.0/MaxLengthConstraint.json"
        )),
    ),
    (
        "MinConstraint.json",
        include_str!(concat!(
            env!("OUT_DIR"),
            "/semantic-core-0.2.0/MinConstraint.json"
        )),
    ),
    (
        "MinLengthConstraint.json",
        include_str!(concat!(
            env!("OUT_DIR"),
            "/semantic-core-0.2.0/MinLengthConstraint.json"
        )),
    ),
    (
        "Multiplicity.json",
        include_str!(concat!(
            env!("OUT_DIR"),
            "/semantic-core-0.2.0/Multiplicity.json"
        )),
    ),
    (
        "NonEmptyConstraint.json",
        include_str!(concat!(
            env!("OUT_DIR"),
            "/semantic-core-0.2.0/NonEmptyConstraint.json"
        )),
    ),
    (
        "OperationDecl.json",
        include_str!(concat!(
            env!("OUT_DIR"),
            "/semantic-core-0.2.0/OperationDecl.json"
        )),
    ),
    (
        "PatternConstraint.json",
        include_str!(concat!(
            env!("OUT_DIR"),
            "/semantic-core-0.2.0/PatternConstraint.json"
        )),
    ),
    (
        "RelationDecl.json",
        include_str!(concat!(
            env!("OUT_DIR"),
            "/semantic-core-0.2.0/RelationDecl.json"
        )),
    ),
    (
        "SemanticId.json",
        include_str!(concat!(
            env!("OUT_DIR"),
            "/semantic-core-0.2.0/SemanticId.json"
        )),
    ),
    (
        "SourceLocus.json",
        include_str!(concat!(
            env!("OUT_DIR"),
            "/semantic-core-0.2.0/SourceLocus.json"
        )),
    ),
    (
        "TypeRef.json",
        include_str!(concat!(
            env!("OUT_DIR"),
            "/semantic-core-0.2.0/TypeRef.json"
        )),
    ),
    (
        "UniqueConstraint.json",
        include_str!(concat!(
            env!("OUT_DIR"),
            "/semantic-core-0.2.0/UniqueConstraint.json"
        )),
    ),
    (
        "UnitSymbol.json",
        include_str!(concat!(
            env!("OUT_DIR"),
            "/semantic-core-0.2.0/UnitSymbol.json"
        )),
    ),
];

/// The embedded bundle for `version`, if any. `"0.1.0"` falls through to
/// `None` like any other unrecognized version — see the module doc comment.
pub fn semantic_core_bundle(version: &str) -> Option<&'static [(&'static str, &'static str)]> {
    match version {
        "0.2.0" => Some(SEMANTIC_CORE_0_2_0),
        _ => None,
    }
}
